# Generated by Django 4.0.4 on 2022-04-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_candidato_estadovotacion_estudiante_tipovotacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='fechaFinal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='votacion',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
    ]
