# Generated by Django 4.0.4 on 2022-04-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_votacion_fechafinal_votacion_fechainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='documentoE',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
