# Generated by Django 4.0.4 on 2022-04-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_estudiante_documentoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='documentoE',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='documento',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
