# Generated by Django 4.0.4 on 2022-04-21 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_estudiante_documentoe_estudiante_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estudiante',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.PROTECT, related_name='estudiante_candidatos', to='app.estudiante'),
            preserve_default=False,
        ),
    ]
