# Generated by Django 4.0.4 on 2022-05-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_voto_votacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='votacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='app.votacion'),
            preserve_default=False,
        ),
    ]
