# Generated by Django 4.0.4 on 2022-05-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_estudiante_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='cargo',
        ),
    ]
