# Generated by Django 4.0.4 on 2022-05-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_estudiante_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='votacion',
            field=models.IntegerField(),
        ),
    ]
