# Generated by Django 4.0.4 on 2022-05-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_voto_candidato_alter_voto_votante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='app.candidato'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='app.votacion'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='votante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votantes', to='app.estudiante'),
        ),
    ]
